/**:
  ros__parameters:
    step_size: 0.5
    safety_distance: 0.4

    map_filename: /root/choral_ws/src/mr_het_coord/maps/orchard.pgm
    map_name: orchard
    paths_filename: none
    map_resolution: 0.025
    map_center:
      - 0.0
      - 0.0

    global_frame: "earth"