/**:
  ros__parameters:
    step_size: 0.25
    safety_distance: 0.4

    map_filename: /root/choral_ws/src/mr_het_coord/maps/forest.pgm
    map_name: forest
    paths_filename: none
    map_resolution: 0.0333
    map_center:
      - 0.0
      - 0.0

    global_frame: "earth"