/**:
  ros__parameters:
    step_size: 3.0
    safety_distance: 0.6

    map_filename: /root/choral_ws/src/mr_het_coord/maps/cave.pgm
    map_name: cave
    paths_filename: "none"
    map_resolution: 0.3
    map_center:
      - 0.0
      - 0.0

    global_frame: "earth"

    cost_scaling: 3.0

    # For the application of the following costs, check base_planner.hpp
    
    # Define accident rates for different traversability levels
    # These values represent accidents per meter (e.g., from manufacturer data)
    lambda_good_trav: 0.00001 # Example: 1 accident every 100000m
    lambda_bad_trav: 0.05 # Example: 1 accident every 50m
    # lambda_bad_trav: 5.0 # Example: 5 accident every 1m / or 1 accident every 0.2m

    # Define parameters for the logistic function in the collision cost
    # These values would be determined experimentally or from manufacturer data
    gamma_collision: 10.0 # Controls the decay rate. Prob is very low at 1m
    d_05_collision: 0.4 # Distance at which the rate is 0.5 (high accident likelihood). We set it to 0.1m