/**:
  ros__parameters:

    global_frame: "earth"

    robot_ns:
      - "drone2"
      - "turtlebot1"

    num_vehicles: 2

    agent_types:
      - AERIAL
      - GROUND
      
    orientations:
      - 0.0
      - 0.0

    velocities:
      - 0.5
      - 0.25

    solver_seconds: 3

    results_path: /root/results/