/**:
  ros__parameters:
    num_vehicles: 4

    agent_types:
      - AERIAL
      - AERIAL
      - GROUND
      - GROUND
    
    orientations:
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    velocities:
      - 1.0
      - 1.0
      - 0.5
      - 0.5

    solver_seconds: 120

    results_path: /root/results/