/**:
  ros__parameters:
    step_size: 1.5
    map_filename: /root/mr_ws/src/het_vrp/maps/map0.pgm
    map_name: map0
    paths_filename: none
    map_resolution: 2.0
    map_center:
      - 0.0
      - 0.0