/**:
  ros__parameters:
    step_size: 0.1
    map_filename: /root/mr_ws/src/het_vrp/maps/office.pgm
    map_name: office
    paths_filename: "none"
    map_resolution: 0.1
    map_center:
      - 0.0
      - 0.0
