/**:
  ros__parameters:
    num_vehicles: 2

    agent_types:
      - AERIAL
      - GROUND
      
    orientations:
      - 0.0
      - 0.0

    velocities:
      - 1.0
      - 0.3

    cost_scaling: 5.0

    # For the application of the following costs, check base_planner.hpp
    
    # Define accident rates for different traversability levels
    # These values represent accidents per meter (e.g., from manufacturer data)
    lambda_good_trav: 0.00001 # Example: 1 accident every 100000m
    lambda_bad_trav: 5.0 # Example: 5 accident every 1m / or 1 accident every 0.2m

    # Define parameters for the logistic function in the collision cost
    # These values would be determined experimentally or from manufacturer data
    gamma_collision: 20.0 # Controls the decay rate. Prob is very low at 1m
    d_05_collision: 0.1 # Distance at which the rate is 0.5 (high accident likelihood). We set it to 0.5m


    solver_seconds: 120

    results_path: /root/results/